kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
mirror:
  platform:
    channels:
    - name: stable-4.19
      type: ocp
      #minVersion: 4.19.6 # optional
      #maxVersion: 4.19.6 # optional
    graph: true
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.19
    packages:
    - name: cluster-logging
      channels:
      - name: stable-6.3
    - name: cluster-observability-operator
      channels:
      - name: stable
    - name: loki-operator
      channels:
      - name: stable-6.3
    - name: compliance-operator
      channels:
      - name: stable
    - name: local-storage-operator
      channels:
      - name: stable
    - name: nfd
      channels:
      - name: stable
    - name: servicemeshoperator
      channels:
      - name: stable
    - name: kialia-ossm-operator
      channels:
      - name: stable
    - name: lvms-operator
      channels:
      - name: stable-4.19
    - name: odf-operator
      channels:
      - name: stable-4.19
    - name: authorino-operator
      channels:
      - name: stable
    - name: jaeger-product
      channels:
      - name: stable
    - name: metallb-operator
      channels:
      - name: stable
    - name: serverless-operator
      channels:
      - name: stable
    - name: openshift-gitops-operator
      channels:
      - name: latest
    - name: openshift-pipelines-operator
      channels:
      - name: latest
    - name: kernel-module-management
      channels:
      - name: stable
    - name: kubevirt-hyperconverged
      channels:
      - name: stable
    - name: rook-ceph-operator
      channels:
      - name: stable-4.19
    - name: kubernetes-nmstate-operator
      channels:
      - name: stable
    - name: quay-bridge-operator
      channels:
      - name: stable-3.15
    - name: quay-operator
      channels:
      - name: stable-3.15
    - name: servicemeshoperator
      channels:
      - name: stable
    - name: servicemeshoperator3
      channels:
      - name: stable
    - name: skupper-operator
      channels:
      - name: stable-2
    - name: sriov-network-operator
      channels:
      - name: stable
    - name: smb-csi-driver-operator
      channels:
      - name: stable
    - name: submariner
      channels:
      - name: stable-0.21
    - name: rhtpa-operator
      channels:
      - name: stable
    - name: rook-ceph-operator
      channels:
      - name: stable-4.19
    - name: web-terminal
      channels:
      - name: fast
  - catalog: registry.redhat.io/redhat/certified-operator-index:v4.19
    packages:
    - name: gpu-operator-certified
      defaultChannel: v25.10
      channels:
      - name: v25.10
  additionalImages:
  # how you include additional images that you want to be part of the mirror download
  - name: registry.redhat.io/rhel9/support-tools:latest
